#threshold_buy = 1.0
#threshold_sell = -1.0
#method = 'adadelta'

#learning_rate = 1.2
#momentum = 0.9
#decay = 0.10
#stoploss_enabled = false
#stoploss_threshold = 0.85
#hodl_threshold = 1
#price_buffer_len = 100
#min_predictions = 1000




threshold_buy = 0.35
threshold_sell = -0.45


learning_rate = 0.01
momentum = 0.1
decay = 0.01
stoploss_enabled = true
stoploss_threshold = 0.85
hodl_threshold = 1
price_buffer_len = 9
min_predictions = 50
